apiVersion: batch/v1
kind: Job
metadata:
  name: clear-queue-job
spec:
  template:
    spec:
      containers:
        - name: clear-queue
          image: sravan1327/order-service:latest
          command: ["node", "src/clearQueue.js"]
      restartPolicy: Never
